#+TITLE: Papers from 2016
#+DESCRIPTION:
#+KEYWORDS:
#+STARTUP:  content
#+OPTIONS: toc:1 H:4 num:1

- [[wiki:index][Index]]
  
* [[https://eprint.iacr.org/2016/208][Constant-Round Asynchronous Multi-Party Computation Based on One-Way Functions (Sandro Coretti and Juan Garay and Martin Hirt and Vassilis Zikas)]]
Presented at ASIACRYPT 2016.
** Short Description
Constant-round MPC in a setting where there is a bound on the delivery time but it is unknown.

** Abstract
Secure multi-party computation (MPC) allows several mutually distrustful parties to securely compute a joint function of their inputs and exists in two main variants: In *synchronous* MPC parties are connected by a synchronous network with a global clock, and protocols proceed in *rounds* with strong delivery guarantees, whereas *asynchronous* MPC protocols can be deployed even in networks that deliver messages in an arbitrary order and impose arbitrary delays on them.

The two models---synchronous and asynchronous---have to a large extent developed in parallel with results on both feasibility and asymptotic efficiency improvements in either track. The most notable gap in this parallel development is with respect to round complexity. In particular, although under standard assumptions on a synchronous communication network (availability of secure channels and broadcast), synchronous MPC protocols with (exact) constant rounds have been constructed, to the best of our knowledge, thus far no constant-round asynchronous MPC protocols are known, with the best protocols requiring a number of rounds that is linear in the multiplicative depth of the arithmetic circuit computing the desired function.

In this work we close this gap by providing the first constant-round asynchronous MPC protocol. Our protocol is optimally resilient (i.e., it tolerates up to $t\lt n/3$ corrupted parties), adaptively secure, and makes black-box use of a pseudo-random function. It works under the standard network assumptions for protocols in the asynchronous MPC setting, namely, a complete network of point-to-point (secure) asynchronous channels with eventual delivery and asynchronous Byzantine agreement (aka consensus). We provide formal definitions of these primitives and a proof of security in the Universal Composability framework.


** My Summary

The authors consider MPC in a setting in which there is a bound on the network delivery time, but it is known by the protocol.
Such setting is called /asynchronous with eventual delivery/, and part of the contribution is formalizing such notion on top of the UC framework by Canetti [[[coretti-1][1]]].
The main challenge is that the original UC framework is message-driven and as such it is inherently /fully asynchronous/ (i.e. the adversary can delay messages indefinitely).
The authors introduce eventual delivery by forcing the adversary to input a bound before the protocol starts, and the functionality delivers messages once they have been requested as many times as this bound mandates (sequential messages are queued).

The authors aim at a constant-round protocol.
Their construction is based on the existence of PRFs and tolerates $t\lt n/3$ corruptions.
At a high level, their construction follows the BMR template for constant-round multiparty computation where the parties use an existing MPC protocol to generate a garbled circuit (Figure 4) and then perform local computation (Figure 5).
In a bit more detail, the parties use the BKR protocol [[[coretti-2][2]]] to compute a garbled version of the circuit (in fact, they use an optimization from Damgard and Ishai [[[coretti-3][3]]] that removes the cipher from the oblivious evaluation using Shamir SS).
The garbling consists of computing the typical garbled table for each gate except that instead of encrypting the message (or wire value), the parties secret-share it and encrypt /locally/ each share.
This approach is very useful given the asynchronous nature of the protocol.
      
*** References
1) <<coretti-1>>Canetti, R.: Universally composable security: A new paradigm for cryptographic protocols. In: 42nd FOCS. pp. 136-145. IEEE Computer Society Press, Las Vegas, Nevada, USA (Oct 14-17, 2001).
2) <<coretti-2>>Ben-Or, M., Kelmer, B., Rabin, T.: Asynchronous secure computations with optimal resilience (extended abstract). In: PODC. pp. 183-192 (1994).
3) <<coretti-3>>Damgård, I., Ishai, Y.: Constant-round multiparty computation using a black-box pseudorandom generator. In: Shoup, V. (ed.) CRYPTO. Lecture Notes in Computer Science, vol. 3621, pp. 378-394. Springer (2005).   

 
* [[https://eprint.iacr.org/2016/768][High-Throughput Semi-Honest Secure Three-Party Computation with an Honest Majority (Toshinori Araki and Jun Furukawa and Yehuda Lindell and Ariel Nof and Kazuma Ohara)]]
Presented at CCS 2016.
** Short Description
Three-party MPC with cheap semi-honest multiplications.

** Abstract
In this paper, we describe a new information-theoretic protocol (and a computationally-secure variant) for secure {\em three}-party computation with an honest majority. The protocol has very minimal computation and communication; for Boolean circuits, each party sends only a single bit for every AND gate (and nothing is sent for XOR gates). Our protocol is (simulation-based) secure in the presence of semi-honest adversaries, and achieves privacy in the client/server model in the presence of malicious adversaries.

On a cluster of three 20-core servers with a 10Gbps connection, the implementation of our protocol carries out over \textit{1.3 million} AES computations per second, which involves processing over \textit{7 billion gates per second}. In addition, we developed a Kerberos extension that replaces the ticket-granting-ticket encryption on the Key Distribution Center (KDC) in MIT-Kerberos with our protocol, using keys/ passwords that are shared between the servers. This enables the use of Kerberos while protecting passwords. Our implementation is able to support a login storm of over 35,000 logins per second, which suffices even for very large organizations. Our work demonstrates that high-throughput secure computation is possible on standard hardware.
  
** My Summary
I didn't read this paper in detail.
The authors propose a secret sharing scheme which resembles replicated SS, although it is a bit different.
To share a secret $v\in\mathbb{Z}_{2^k}$ in their scheme, each party $P_i$ for $i=1,2,3$ has a masked version of $x$, $a_i=x_i-v\bmod 2^k$, where the $x_i$'s are random but conditioned on $x_1+x_2+x_3=0\bmod 2^k$
$P_i$ also has the 'key' $x_{i+1}$.
It is easy to see that any pair of parties can reconstruct the secret, but no single party learns anything about it.

The scheme above is clearly linearly homomorphic.
To handle multiplications, it is assumed that the parties have correlated randomness $\alpha,\beta,\gamma$ such that $\alpha+\beta+\gamma = 0$.
These can be preprocessed easily by pre-agreeing on certain keys for a PRF (e.g. AES) and then using the PRF in a non-interactive manner to generate the correlated randomness.
The multiplication itself is rather short and I suggest reading it directly from the paper in Section 2.3.
